### ISSUE TITLE
file structure might still be too messy

### ISSUE THREAD

**Issue by mirmirmirr** [RPI-ITWS/ITWS-2110-F24-LuckyCharms#24]
Currently, the current file structure has a pages directory that contains files for each page other than the landing page of the site. Billy suggests that it might be good to restructure this directory so that we have subfolders for each page and then an index.html that displays the information for that page like so:
`/pages /login/ index.html`

This is something that should be discussed with the rest of the team at some point.

**Comment by hemanskolla** [comment]
Billy created this PR #27 . I will test locally and merge. This issue will be closed at that point.

**Comment by hemanskolla** [comment]
Merged. We can reopen as—if—problems arise.
