### ISSUE TITLE
Item details don't disappear when switching between labs

### ISSUE THREAD

**Issue by BradsherC** [RPI-ITWS/ITWS-2110-F24-LuckyCharms#42]
If you login with the info of the fake user John Miller (who has access to multiple labs), select "sewing machine" in The Forge to open the item's details, then click "Mercer Lab" to show that lab's inventory. Even though you are now looking at a lab with no sewing machine, that item's details are still shown.

**Comment by SuperUltraMegaChicken** [comment]
Fixed in #36
