### ISSUE TITLE
Constant "Guest" name despite being logged in 

### ISSUE THREAD

**Issue by mirmirmirr** [RPI-ITWS/ITWS-2110-F24-LuckyCharms#43]
In the backend branch, after we login, the hamburger menu popup still displays "Guest" instead of the actual users name.

![image](https://github.com/user-attachments/assets/1a8322ca-0cee-414f-9ed7-792d2296ed65)

**Comment by mirmirmirr** [comment]
maybe we can also have the session variables store the username to pass around?

**Comment by SuperUltraMegaChicken** [comment]
- This has been fixed in the backend branch


> maybe we can also have the session variables store the username to pass around?

That could work, although there is a dedicated query for it.
