### ISSUE TITLE
borrowing history table problem

### ISSUE THREAD

**Issue by mirmirmirr** [RPI-ITWS/ITWS-2110-F24-LuckyCharms#68]
Within the borrowing history tab, it shows the user's name and the "User" column even though it this column should've only been visible for admins according to the code:

```  document.getElementById("table-head").innerHTML = `
    ${isAdmin ? "<th><p>User</p></th>" : ""}
    <th><p>Item Name</p></th>
    <th><p>Lab</p></th>
    <th>Amount</th>
    <th>Status</th>
    <th>Reservation Date</th>
    <th>Expected Return Date</th>
    ${getAll ? "<th>Date Returned/Cancelled</th>" : ""}
    ${isAdmin && !getAll ? "<th>Actions</th>" : ""}
  `;```

**Comment by BradsherC** [comment]
for me it does this when I first go to that page, but when I switch to the "currently borrowing" tab and switch back it resolves

**Comment by SuperUltraMegaChicken** [comment]
The issue involves the fetching converting the numbers to strings and all non empty strings are truthy values.
